Develop
iamChukka/to-do pull request #5
Opened 2022-04-29 13:12 UTC by iamChukka

2022-04-29 13:13 UTC, iamChukka commented
Check out my Pull Requests @iamChukka moving to Typescript

2022-04-29 13:40 UTC, albert-lunchbox reviewed
add dist to your gitignore since it can be generated any time

2022-05-02 09:12 UTC, albert-lunchbox commented on src/controllers/authControllers.ts
>        return res.send(token);
try to use res.status(code).json({ message: 'this is a message', data: {}})
code: 
200 for getting, updating resource
201: for creating resource
422: Validation error
400: Bad request
401: Unauthorised operation
403:------
404: Not found error
@iamChukka

2022-05-02 09:13 UTC, albert-lunchbox commented on src/controllers/authControllers.ts
>        return res.send(token);
you can create like a constant file where you put the code inside an object an export to be used everywhere. Reusability pattern

2022-05-02 09:14 UTC, albert-lunchbox commented on src/controllers/userControllers.ts
>        return res.status(error.code).json(error.message);
following the pattern i discussed before

2022-05-02 09:18 UTC, albert-lunchbox commented on src/controllers/userControllers.ts
>        return res.status(error.code).json(error.message);
And be consistent every where, or you can create a function for response and resuse it everywhere

const Response = ({ res, code, message, data, token }) => res.status(code).json({ message, data, token })

2022-05-02 09:44 UTC, rkterungwa16 requested changes

2022-05-02 09:44 UTC, rkterungwa16 commented on src/controllers/authControllers.ts
> +function validate(req: any) {
Avoid using `any` as a type as much as possible

2022-05-02 09:44 UTC, rkterungwa16 commented on src/controllers/todoControllers.ts
> +  static async createTodo(req: any, res: any) {
same here, always use the proper types rather than using `any`

2022-05-02 09:44 UTC, rkterungwa16 commented on src/controllers/todoControllers.ts
> +  static async getTodosByUserId(req: any, res: any) {
Same here avoid using `any` here

2022-05-02 09:44 UTC, rkterungwa16 commented on src/controllers/todoControllers.ts
> +  static async updateTodo(req: any, res: any) {
Avoid using `any` here

2022-05-02 09:44 UTC, rkterungwa16 commented on src/controllers/authControllers.ts
> +class customError extends Error {
Abstract the custom error to a single module that can be used by all controllers.

2022-05-02 09:44 UTC, rkterungwa16 commented on src/controllers/userControllers.ts
> +class customError extends Error {
Abstract the `customError` into a single module that can be used by all controllers

2022-05-02 09:44 UTC, rkterungwa16 commented on src/controllers/userControllers.ts
> +  static async createUser(req: any, res: any, next: any) {
Avoid using `any` here

2022-05-02 09:44 UTC, rkterungwa16 commented on src/controllers/userControllers.ts
> +const createError = (msg: string, code: any) => {
avoid using `any` here

2022-05-02 09:44 UTC, rkterungwa16 commented on src/controllers/userControllers.ts
> +  constructor(msg: string, code: any) {
avoid using `any` here

2022-05-02 09:44 UTC, rkterungwa16 commented on src/models/User.ts
> +function validateUser(user: any) {
avoid using `any` here

2022-05-02 23:06 UTC, iamChukka commented
created error and response handlers @albert-lunchbox @albert85 . still confused with regulating types @rkterungwa16

2022-05-13 14:34 UTC, merged